### ISSUE TITLE
reportError function

### ISSUE THREAD

**Issue by rrsergeynikiforov** [kaliberjs/firebase-queue#11]
I have a question

```js
const queue1 = new Queue({ tasksRef, processTask:processTask1, reportError, options:options1 })
```

Why don't we use `reportError`?

```js
async function processTask1(task) {
  try {
    // do the work and optionally return a new task
    doSomething();
  } catch (e) {
    reportError(e)
    throw e // this marks the task as failed
  }
}
```

like this, we are calling `reportError` manually.
in `new Queue`, Why don't we use `reportError` as parameter?

**Comment by EECOLOR** [comment]
@rrsergeynikiforov Thank you for the input.

I am not sure I understand you correctly. Do you mean that instead of this:

```js
async function processTask(task) {
   try { ... }
   catch (e) { reportError(e); ... }
}
```

You want to do this:
```js
async function processTask(task, { reportError }) {
   try { ... }
   catch (e) { reportError(e); ... }
}
```

If that is the case I really like your suggestion! If you mean something else, please try to explain it some more, maybe with an example.

**Comment by EECOLOR** [comment]
Ahh, now I understand.

The reportError function is used (at the time of writing) in a few places:

https://github.com/kaliberjs/firebase-queue/blob/master/src/queue_worker.js#L21
```js
newTaskRef.on('child_added', tryToProcessAndCatchError, reportError)
```

and

https://github.com/kaliberjs/firebase-queue/blob/master/src/queue_worker.js#L32
```js
await claimAndProcess(ref).catch(reportError)
```

It is essentially a way for the library to report a problem. The original library swallowed a lot of errors. So if you, for example, had a problem in one of your rules, the original firebase-queue would pretend everything is ok while it was not working.

There is a slight difference between typing the try/catch and not typing it within the `processTask` function .

```js
// set the error state on the task when an error occurs, but don't report it
async function processTask(task) {
   ...
}
```

```js
// report the error and set the error state on the task when an error occurs
async function processTask(task) {
   try { ... }
   catch (e) { reportError(e); throw e }
}
```

```js
// report the error and complete the task normally when an error occurs
async function processTask(task) {
   try { ... }
   catch (e) { reportError(e) }
}
```

In some use cases we do not put our code into a try/catch block because the error is part of the application flow. The client (that created the task) will give the user feedback, so there is no need to report the error (to rollbar).

We could theoretically add a queue option:

```js
new Queue({ options: { reportErrorsFromProcessTask: true/false }, ... })
```

The following snippets would then be equivalent (the same):

```js
new Queue({ options: { reportErrorsFromProcessTask: true }, ... })
...
async function processTask(task) {
   ...
}
```
```js
new Queue({ options: { reportErrorsFromProcessTask: false }, ... })
...
async function processTask(task) {
   try { ... }
   catch (e) { reportError(e); throw e }
}
```

**Comment by itdev123** [comment]
It's good
Thanks
and I have another question
    const options = {
      spec: stage,
      numWorkers: workersetting.count
    };

I set numWorkers like this but I found a worker was only running at the same time.
Could you check again?

**Comment by EECOLOR** [comment]
@itdev123 I have moved you new question here: https://github.com/kaliberjs/firebase-queue/issues/12

@itdev123 are you and @rrsergeynikiforov the same person?

**Comment by EECOLOR** [comment]
I have opened two feature requests that came from this thread, vote for them if you want to see them added: #13 #14

**Comment by EECOLOR** [comment]
@geoervin Good idea! The comment contained multiple sections. Would you be willing to adjust the documentation in way that makes it clear to you in a pull request?
